# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: run-script

on:
  workflow_dispatch:
  schedule:
  - cron: "55 1 * * 1-5"
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
          # Checkout the branch
          - name: checkout
            uses: actions/checkout@v2
            with: 
              token: ${{ secrets.MY_PAT }}
              fetch-depth: 0
    
    
          - name: Set up Python 3.9
            uses: actions/setup-python@v2
            with:
              python-version: 3.9
              
          - name: setup git config
            run: |
              git config user.name "Ted Marozzi"
              git config user.email "<>"
        
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
          - run: |
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
              echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
              sudo apt-get update -qqy
              sudo apt-get -qqy install google-chrome-stable
              CHROME_VERSION=$(google-chrome-stable --version)
              CHROME_FULL_VERSION=${CHROME_VERSION%%.*}
              CHROME_MAJOR_VERSION=${CHROME_FULL_VERSION//[!0-9]}
              sudo rm /etc/apt/sources.list.d/google-chrome.list
              export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
              curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
              unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
              export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
              curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
              unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
              chromedriver -version
            shell: bash
           
          - name: Install jq
            run: |
              sudo apt-get install jq
              
          - name: Make secret
            run: |
              jq -n --arg bn "${{ secrets.FB_USER_NAME }}" --arg pw "${{ secrets.FB_PASSWORD }}" '{Username: $bn, Password: $pw}' > secret.json
              
              
          - name: Run Script
            run: |
              python stockscrape.py
              
          - name: Commit
            run: |
              git fetch --all
              git pull --ff-only
              git add -A
              git commit -m "Another day another Stonk Scrape"
              git push
